remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Sarthak Jain - Hardware Engineering Portfolio
description: USC EE MS (Computer Architecture) 2025 | FPGA Design Engineer
include:
  - custom.css
