title: Sarthak Jain - Hardware Engineering Portfolio
description: USC EE MS 2025 | FPGA Design Engineer | Computer Architecture
baseurl: ""
url: "https://SARTHAK-JAIN-ASIC.github.io"
theme: jekyll-theme-chirpy
